import { useState } from "react"
import { Card, FormField, Loader } from "../Components"

const RenderCards=({data,title})=>{
  if(data?.length>0){return data.map(post=>(
    <Card key={post._id} {...post}/>
  ))}
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase" >
      {title}

    </h2>
  )
}

 
const Home = () => {

    const [isloading,setIsloading]=useState(false)
    const [allPosts,setAllPosts]=useState(null)
    const [searchText,setSearchText]=useState('')
  return (
    <section className="max-w-7xl mx-auto ">
       <div>
        <h1 className="font-extrabold text-gray-800 text-[32px]">
           The Community Showcase
        </h1>
        <p className="mt-2 text-gray-700 text-[17px] max-w-[800px]">
           Browse through a colection of imaginative and visually stunning images generated by Open AI
        </p>
       </div>
       <div>
        <FormField/>
       </div>
       <div className="mt-10">
        {isloading?
        <div className="flex justify-center items-center">
         <Loader/>   
        </div>:<>
        {searchText && (<h2>
           Showing results for <span>
            {searchText}
           </span>
          </h2>) }
         <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">


          {searchText?
          <RenderCards data={[]}
           title='No search result found'
          /> :(
            <RenderCards data={[]} title='There are no post available'/>
          )}


         </div>


        </>}

       </div>
    </section>
  )
}

export default Home